apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/operation-id: 3240cddc-261d-48b3-8521-a24928e4a9a2
    run.googleapis.com/urls: '["https://api-gateway-prod-780842550857.us-central1.run.app"]'
    serving.knative.dev/creator: rubenmeister@gmail.com
    serving.knative.dev/lastModifier: rubenmeister@gmail.com
  creationTimestamp: '2026-01-11T02:13:20.227255Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
  name: api-gateway-prod
  namespace: '780842550857'
  resourceVersion: AAZIE02EFT4
  selfLink: /apis/serving.knative.dev/v1/namespaces/780842550857/services/api-gateway-prod
  uid: 017bd641-9b0b-4b73-b50b-1c756326e5f6
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/vpc-access-connector: vpc-conn-prod
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: BOOKING_SERVICE_URL
          value: https://booking-service-prod-us-central1.a.run.app
        - name: PARCEL_SERVICE_URL
          value: https://parcel-service-prod-us-central1.a.run.app
        - name: TOURS_SERVICE_URL
          value: https://tours-service-prod-us-central1.a.run.app
        - name: USER_AUTH_SERVICE_URL
          value: https://user-auth-service-prod-us-central1.a.run.app
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: JWT_SECRET-prod
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: DATABASE_URL-prod
        - name: TRANSPORT_SERVICE_URL
          value: https://transport-service-prod-us-central1.a.run.app
        - name: PAYMENT_SERVICE_URL
          value: https://payment-service-prod-us-central1.a.run.app
        - name: EXPERIENCE_SERVICE_URL
          value: https://experience-service-prod-us-central1.a.run.app
        - name: HOST_SERVICE_URL
          value: https://host-service-prod-us-central1.a.run.app
        - name: TRACKING_SERVICE_URL
          value: https://tracking-service-prod-us-central1.a.run.app
        - name: NOTIFICATIONS_SERVICE_URL
          value: https://notifications-service-prod-us-central1.a.run.app
        image: us-central1-docker.pkg.dev/going-5d1ae/going-repo-prod/api-gateway:latest
        ports:
        - containerPort: 3000
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 3000
          timeoutSeconds: 240
      serviceAccountName: 780842550857-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  conditions:
  - lastTransitionTime: '2026-01-11T02:13:22.300826Z'
    message: 'spec.template.spec.containers[0].env[5].value_from.secret_key_ref.name:
      Failed to access secret projects/780842550857/secrets/JWT_SECRET-prod/versions/latest:
      Secret Version [projects/780842550857/secrets/JWT_SECRET-prod/versions/1] is
      in DESTROYED state.'
    reason: SecretsAccessCheckFailed
    status: 'False'
    type: Ready
  - lastTransitionTime: '2026-01-11T02:13:21.627236Z'
    message: 'spec.template.spec.containers[0].env[5].value_from.secret_key_ref.name:
      Failed to access secret projects/780842550857/secrets/JWT_SECRET-prod/versions/latest:
      Secret Version [projects/780842550857/secrets/JWT_SECRET-prod/versions/1] is
      in DESTROYED state.'
    reason: SecretsAccessCheckFailed
    status: 'False'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-01-11T02:13:22.300826Z'
    message: 'spec.template.spec.containers[0].env[5].value_from.secret_key_ref.name:
      Failed to access secret projects/780842550857/secrets/JWT_SECRET-prod/versions/latest:
      Secret Version [projects/780842550857/secrets/JWT_SECRET-prod/versions/1] is
      in DESTROYED state.'
    reason: SecretsAccessCheckFailed
    status: 'False'
    type: RoutesReady
  latestCreatedRevisionName: api-gateway-prod-00001-fns
  observedGeneration: 1
